[package]
name = "dutree"
version = "0.2.1"
authors = ["nacho <nacho@ownyourbits.com>"]

[dependencies]
dict = "0.1.1"
getopts = "0.2"
terminal_size= { git = "https://github.com/eminence/terminal-size.git" }
regex = "0.2"
unicode-width = "0.1.1"
